server:
  port: 8088

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 59ea27d2
    url: jdbc:mysql://localhost:3306/mmall?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml